version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: guate-trivia-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql  # Persiste los datos de la base de datos (opcional)
      # - ./scripts:/docker-entrypoint-initdb.d # Ubicación de los scripts de inicialización
    ports:
      - "3306:3306"